### ISSUE TITLE
Error No module named 'websauna.compat' 

### ISSUE THREAD

**Issue by highPriestLOL** [websauna/websauna.blog#2]
Running ws-* commands don't work anymore. On python 3.5 or 3.6, throwing the error below.

```
(venv) anthony@bellwether:/opt/websauna/websauna.blog$ ws-sync-db websauna/blog/conf/development.ini 
Traceback (most recent call last):
  File "/opt/websauna/websauna.blog/venv/bin/ws-sync-db", line 7, in <module>
    from websauna.system.devop.scripts.syncdb import main
  File "/opt/websauna/websauna.blog/venv/lib/python3.5/site-packages/websauna/system/__init__.py", line 5, in <module>
    from websauna.system.mail.utils import create_mailer
  File "/opt/websauna/websauna.blog/venv/lib/python3.5/site-packages/websauna/system/mail/__init__.py", line 13, in <module>
    from websauna.system.http import Request
  File "/opt/websauna/websauna.blog/venv/lib/python3.5/site-packages/websauna/system/http/__init__.py", line 9, in <module>
    from websauna.system.admin.admin import Admin
  File "/opt/websauna/websauna.blog/venv/lib/python3.5/site-packages/websauna/system/admin/admin.py", line 6, in <module>
    from websauna.system.admin import menu
  File "/opt/websauna/websauna.blog/venv/lib/python3.5/site-packages/websauna/system/admin/menu.py", line 4, in <module>
    from websauna.compat.typing import Callable
ImportError: No module named 'websauna.compat'

```

**Comment by highPriestLOL** [comment]
```
pip install --upgrade pip setuptools
pip install -e "git+https://github.com/websauna/websauna.git@master#egg=websauna[celery,utils,notebook]"
```
